# Generated by Django 4.1.5 on 2023-01-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilsynsbesoektype', models.CharField(max_length=255)),
                ('postste', models.CharField(max_length=255)),
                ('sakref', models.CharField(max_length=255)),
                ('tilsynsobjektid', models.CharField(max_length=255)),
                ('orgnummer', models.CharField(max_length=255)),
                ('postnr', models.CharField(max_length=255)),
                ('dato', models.CharField(max_length=255)),
                ('navn', models.CharField(max_length=255)),
                ('tema1_no', models.CharField(max_length=255)),
                ('tema3_nn', models.CharField(max_length=255)),
                ('tema1_nn', models.CharField(max_length=255)),
                ('tema3_no', models.CharField(max_length=255)),
                ('tilsynid', models.CharField(max_length=255)),
                ('adrlinje1', models.CharField(max_length=255)),
                ('karakter1', models.CharField(max_length=255)),
                ('adrlinje2', models.CharField(blank=True, max_length=255, null=True)),
                ('karakter2', models.CharField(max_length=255)),
                ('karakter3', models.CharField(max_length=255)),
                ('karakter4', models.CharField(max_length=255)),
                ('total_karakter', models.CharField(max_length=255)),
                ('tema4_no', models.CharField(max_length=255)),
                ('tema4_nn', models.CharField(max_length=255)),
                ('tema2_n0', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('tema2_nn', models.CharField(max_length=255)),
            ],
        ),
    ]
