# Generated by Django 4.1.5 on 2023-01-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='postste',
            new_name='poststed',
        ),
    ]
