# Generated by Django 4.1.5 on 2023-02-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_postste_restaurant_poststed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='tema2_n0',
            new_name='tema2_no',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='karakter1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='karakter2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='karakter3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='karakter4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
